export const MOCK_EMAILS = [
  {
    id: "msg-101",
    threadId: "thread-101",
    sender: "HR Team <hr@techinnovators.com>",
    senderEmail: "hr@techinnovators.com",
    recipient: "user@gmail.com",
    subject: "Internship Technical Interview — Schedule & Next Steps",
    snippet: "Thank you for applying to the Full-Stack Developer Internship. We would like to schedule your technical interview...",
    body: `Dear Charan,\n\nThank you for your application to the Full-Stack AI Developer Internship position at TechInnovators.\n\nWe were very impressed by your background and project portfolio. We would like to invite you for a 45-minute technical interview scheduled for:\n\nDate: Wednesday, September 4, 2026\nTime: 10:00 AM IST\nFormat: Google Meet (link will be sent upon confirmation)\n\nRequired Documents before September 1:\n1. Updated PDF Resume\n2. Government Issued ID Proof\n3. Links to your GitHub repositories\n\nPlease confirm your availability for September 4 by responding to this email before Monday.\n\nBest regards,\nAnanya Sharma\nSenior Technical Recruiter | TechInnovators Inc.`,
    date: "10:32 AM",
    isRead: false,
    isStarred: true,
    isArchived: false,
    isDeleted: false,
    category: "Internship",
    priority: "High",
    hasAttachments: true
  },
  {
    id: "msg-102",
    threadId: "thread-102",
    sender: "Prof. K. R. Varma <krvarma@university.edu>",
    senderEmail: "krvarma@university.edu",
    recipient: "student@gmail.com",
    subject: "CSE402 Assignment Submission & Exam Schedule Notice",
    snippet: "Please be reminded that Assignment 3 must be submitted to the online portal before Friday August 28...",
    body: `Dear Class,\n\nThis is an important reminder regarding CS402 Advanced Web Engineering.\n\n1. Assignment 3 (FastAPI & Database Integration) deadline is set for Friday, August 28 at 11:59 PM.\n2. The Mid-Term Examination is scheduled for September 10 at Exam Hall B.\n\nLate submissions will incur a 10% penalty per day. Make sure to test your code locally before pushing to GitHub.\n\nRegards,\nProf. K. R. Varma\nDepartment of Computer Science`,
    date: "Yesterday",
    isRead: false,
    isStarred: false,
    isArchived: false,
    isDeleted: false,
    category: "Academic",
    priority: "High",
    hasAttachments: false
  },
  {
    id: "msg-103",
    threadId: "thread-103",
    sender: "Bank of Baroda Alerts <alerts@bankofbaroda.co.in>",
    senderEmail: "alerts@bankofbaroda.co.in",
    recipient: "user@gmail.com",
    subject: "E-Statement for Account Ending XXXX4210 — July 2026",
    snippet: "Your monthly e-statement for the period July 1 to July 31 is attached herewith...",
    body: `Dear Customer,\n\nYour electronic statement for account ending in XXXX4210 for the month of July 2026 has been generated.\n\nAccount Balance: ₹45,210.00\nTotal Credits: ₹15,000.00\nTotal Debits: ₹8,450.00\n\nTo open the PDF attachment, use your 8-digit date of birth as the password.\n\nThank you for banking with Bank of Baroda.`,
    date: "Aug 20",
    isRead: true,
    isStarred: false,
    isArchived: false,
    isDeleted: false,
    category: "Finance",
    priority: "Medium",
    hasAttachments: true
  },
  {
    id: "msg-104",
    threadId: "thread-104",
    sender: "Google Cloud Platform <no-reply@cloud.google.com>",
    senderEmail: "no-reply@cloud.google.com",
    recipient: "user@gmail.com",
    subject: "Monthly Cloud Usage Summary & OAuth Verification Status",
    snippet: "Your Google Cloud project IntelliMail has consumed $0.00 of your free tier credits...",
    body: `Hello GCP Administrator,\n\nHere is your monthly project summary for project: IntelliMail (id: intellimail-prod-2026).\n\n- Gmail API Status: Active\n- Firebase Firestore Status: Active\n- Current Billing: $0.00 / Free Tier Active\n\nReminder: If you are preparing for public launch, make sure to submit your OAuth consent screen for verification if using restricted scopes.\n\nGoogle Cloud Platform Team`,
    date: "Aug 18",
    isRead: true,
    isStarred: true,
    isArchived: false,
    isDeleted: false,
    category: "Important",
    priority: "Low",
    hasAttachments: false
  },
  {
    id: "msg-105",
    threadId: "thread-105",
    sender: "CourseHub Marketing <news@coursehub.io>",
    senderEmail: "news@coursehub.io",
    recipient: "user@gmail.com",
    subject: "Special Discount: 50% Off Full-Stack Web Development Masterclass",
    snippet: "Limited time promotion for developer courses. Click to claim discount...",
    body: `Hello Developer,\n\nUpgrade your technical skills with our Full-Stack AI Web Development masterclass!\n\nGet 50% off all enrollments this week only.\n\nBest regards,\nCourseHub Team`,
    date: "Aug 15",
    isRead: true,
    isStarred: false,
    isArchived: false,
    isDeleted: true,
    category: "Promotional",
    priority: "Low",
    hasAttachments: false
  }
];
